### ISSUE TITLE
0.1.1 - Setup Gradle for the project

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#1]
**Description**
For this issue, we should setup the project architecture. As a clean architecture. Have different modules.

**Todo**
- [x] Make the structure of the project
- [x] setup gradle for the project
- [x] have all the dependencies in the main gradle
- [x] make sure all the basics would run
- [x] document the changes

**Comment by M-ds** [comment]
Have a look in the older Dashboard with the current dependencies, and utilise these too in this project.

**Comment by M-ds** [comment]
https://kotlindays.com/2019/12/06/multi-module-spring-boot-in-kotlin-dsl/index.html
