### ISSUE TITLE
0.1.1 - Add Mini.css to the application instead of Skeleton

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#11]
**Description**
To get started we used Skeleton.css, and this was fine for the beginning. However, as we want to process with the application and the layout. I've decided to change up the css style and utilise Mini.css as this is still very minimal (and this is the purpose of the project). 
Plus it should be easy to implement according to the site.

**Todo**
- [x] Remove the Skeleton.css
- [x] Add Mini.css (Scss) to the project
- [x] Apply the same styling as previously
