### ISSUE TITLE
0.1 - JWT implementation

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#17]
**Description**
To keep track of the current user in the application, we should have some sort of token to keep track of the user. We are going to use JWT.
[Link](https://bezkoder.com/spring-boot-vue-js-authentication-jwt-spring-security/)

**Todo**
- [x] create a sample repo
- [x] use the JWT in cookies (for exercise purposes)
- [x] describe the process in the readme / wiki..
- [x] implement the working solution 
- [x] make the frontend work with the JWT Token as well
- [x] Store the token in the frontend and send with each request after a login
