### ISSUE TITLE
0.1 - Send create a new user when someone tries to sign up

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#18]
**Description**
Make sure a new user can be signed up once this option is chosen.

**Todo**
- [x] Make validations on the input in the frontend
- [x] send the data from the frontend to the backend
- [x] validate the data
- [x] if the data is incorrect send back an message
- [x] save the new user
- [x] Make sure the correct role is assigned to the person
- [x] display error message if error occures in backend
- [x] send a notification once done

**Comment by M-ds** [comment]
We're not going to replace the frontend framework at the moment. I think it's not the best descision for now. Perhaps we should look into creating a simple one ourselves. But for now this is not the way to go.

**Comment by M-ds** [comment]
https://openbase.com/js/vue-notification
