### ISSUE TITLE
0.1 - Once a new user want to sign up we should send mail for conformation

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#19]
**Description**
Once we have a new user, after the registration process we should return a conformation. And an email should be sent then. In order to validate the user.

**Todo**
- [x] after all the check are correct and email should be sent
- [x] user should confirm and be able to login
- [x] Display a screen once successful 
- [x] Display a screen with the error if one would occure
- [x] Once a new token is requested, just display the current page
- [x] add more unit tests for this part of the program (verification and check)

**Comment by M-ds** [comment]
Once saved: bCryptPasswordEncoder.encode(userDto.getPassword())

**Comment by M-ds** [comment]
useful link: https://www.baeldung.com/security-spring

**Comment by M-ds** [comment]
We gaan voor die conformatie gebruik maken van Thymeleaf. Omdat ik nu niet weet hoe ik het anders kan oplossen. Ik krijg het niet zo goed voor elkaar op dit moment.
