### ISSUE TITLE
0.1 - Existing user

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#20]
**Description**
If an existing user wants to login, the username and password should be checked in the database. And if these are known, the user should be able to go to the next page (dashboard).

**Todo**
- [x] Be able to login with existing user (JWT token)
- [x] Store JWT in the frontend
- [x] Sent JWT token to next request (layout loading)
- [x] Display layout after valid JWT token
- [x] add validations in the frontend
- [x] add validations in the backend
- [x] document the process
