### ISSUE TITLE
0.1 - Existing user should be able to login

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#21]
**Description**
Once a user is known in the application, this person should be able to login

**Todo**
- [x] Person should be able to login with the user name only
- [x] Validate of the user is in the database
- [x] If user is known the dashboard should be displayed
