### ISSUE TITLE
0.1 - Database schema changes

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#24]
**Description**
Refactor the initial database script, so it is complient with the dev database. Also the liquibase scripts should be ignored for now. 
As we need a solid basis for a first deployment. 

**TODO**
- [x] Change id to UUID in database & Throughout the application
- [x] Apply all liquibase changes in the database script
- [x] create 3 inital persons with different roles
- [x] create the sign up date as well for the differen persons. 
- [x] document the new database schema
