### ISSUE TITLE
0.1 - Existing user should be able to login and directed to their personal layout

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#25]
**Description**
Once a user is known, and goes through the flow of validation.
If this is successful, the user should be automatically redirected to their person overview page with all their interactables.

**TODO**
- [ ] once logged in be redirected the interactable overview
- [ ] revisit the database schema
- [ ] load the person interactable overview
