### ISSUE TITLE
0.1 - Create one correct docker container for development

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#28]
**Description**
Now I've created several different containers, some for test purposes, and others were 'the correct one' but now am not sure which one is correct anymore. Thus I've deleted all containers, and now a new one can be created. Which should have all the correct tables too. 
Therefore this issue is closely related to #24.

**Todo**
- [x] apply all changes from #24 
- [x] create a new script if not done already
- [x] create new container
- [x] document in the documentation
