### ISSUE TITLE
0.1.1 - Setup the Codacademy for the project

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#3]
**Description**
Setup the codacademy for the project. Furthermore, also the code reports should also be send to the application.

**Todo**
- [x] Setup the repository
- [x] send the report to Codacademy
- [x] send the reports after each GitHub push

**Comment by M-ds** [comment]
https://medium.com/@pierodibello/adding-jacoco-code-coverage-measurement-to-a-kotlin-gradle-project-and-then-adding-coverage-491d99990d63

https://medium.com/@ranjeetsinha/jacoco-with-kotlin-dsl-f1f067e42cd0

**Comment by M-ds** [comment]
https://github.com/gradle/kotlin-dsl-samples/tree/master/samples
