### ISSUE TITLE
0.1 - Research TypeScript in stead of JavaScript

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#35]
**Description**
Have look how we could implement TypeScript instead of JavaScript. This is to utilise the static typing with TypeScript and perhaps also learn a bit more with TypeScript. 

This could help in the future to more easily develop the frontend within this application.
**TODO**
- [ ] Research what the difference is
- [ ] Would this be the best option
- [ ] How much time would it cost to convert
- [ ] Try to implement this is in the current project
- [ ] Test

**Comment by M-ds** [comment]
Not sure if this will be implemented now.
Therefore issue will be closed.
