### ISSUE TITLE
0.1.1 - Setup Vue for the project

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#4]
**Description**
Add Vue to the project, with other dependencies as well.

Furthermore, make sure you also have a simple login screen just for the aesthetic. This would be good to implement to know for sure if everything would work as expected.
This would consist of two simple input fields (to login, or an option to create  a new account -> redirect to another page).

**Todo**
- [x] Install all the dependencies to the project underneath
- [x] Vue 2.0
- [x] Vue Router
- [x] Vuex
- [x] Axios
- [x] create simple login
- [x] Implement MINI.css to the project as well
