### ISSUE TITLE
0.1 - Review the code written so far for inconsistencies

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#40]
**Description**
To move forward with the project. It would be a good practice to review all the code written so far. And start with a refactoring for the currently written code. As there are bound to be inconsistencies over the past months.
Therefore, we need to refactor the code, and write a lot of tests for all the parts of the project.
**Todo**
- [ ] refactor the structure of the project 
- [ ] refactor the backend if necessary
- [ ] write tests for all the backend stuff
- [ ] review for inconsistencies in the frontend
- [ ] do we need tests for the frontend..?
