### ISSUE TITLE
Rewrite the frontend with Vue

### ISSUE THREAD

**Issue by M-ds** [M-ds/Dashboard#47]
**Description**
The frontend should be re-written in Vue. As this would be a good practise to get better with Vue. 
Furthermore this is also a good start to extend the functionalities with the frontend in the long run.

**TODO**
- [x] Make an example
- [x] Move the existing componts to the front-end
- [ ] Test if everything is still working
- [ ] Document
- [x] Merge to the master branch
