### ISSUE TITLE
2.1 - When clicking on the weather forecast, an new page should be loaded (on the right column)

### ISSUE THREAD

**Issue by M-ds** [M-ds/Dashboard#56]
**Description**
Have a look at the following link when implementing routing in the application.

https://www.springboottutorial.com/spring-boot-vue-full-stack-crud-maven-application
--> Chapter: Implementing Routing

Also make sure the weatherforecast is also working correctly. 

**Todo**
- [x] Make a dummy page, which can be shown when clicked on the weather forecast
- [x] Make sure you can also go back to the overview (Dashboard)
- [x] #66 - Make sure the data is also transformed.
- [x] #68 - Display the weather forecast
- [x] #67 - Different markkup
- [x] #70 - Only save when opening new screen
- [x] #71 - Different colour for the editor

**Comment by M-ds** [comment]
https://stackoverflow.com/questions/46816098/how-to-get-data-from-ckeditor-5-instance

**Comment by M-ds** [comment]
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html

**Comment by M-ds** [comment]
Step 1: 
Add vuex to the project

Step 2: 
Create an interval which save the data from the editor, and store it in the store
https://renatello.com/vue-js-polling-using-setinterval/

Step3: 
Make sure the data is pulled from the vuex store, and displayed in the different editors.

**Comment by M-ds** [comment]
Misschien eens verdiepen in dit: https://github.com/davidroyer/vue2-editor !!

Krijg het namelijk niet goed werkend met de juiste dingen van Editor
