### ISSUE TITLE
0.1.1 - Setup Postgresql for the project

### ISSUE THREAD

**Issue by M-ds** [M-ds/dashboard#6]
**Description**
Setup Postgresql for this project.  Also think about the project and how it should look like. Think about the different relations between the different components of the project. Thus the User table, Interactable table and what should be there even more? InteractableDefault (for all the default values filled in in this table). InteractableMember (with all the custom made interactables). Also a role table perhaps?

**Todo**
- [x] Create a database schema (which can still be adjusted later on ofcourse)
- [x] Create the basic data schema
- [x] Create a docker image for all this information
- [x] Document the process, and the schema

**Comment by M-ds** [comment]
--> use this for starting a local container. [Link to article](https://wkrzywiec.medium.com/database-in-a-docker-container-how-to-start-and-whats-it-about-5e3ceea77e50)
--> [Older project](https://github.com/M-ds/Dashboard-v1/tree/clean-architecture/docker)
