### ISSUE TITLE
Make the technical documentation part of the GitHub Wiki

### ISSUE THREAD

**Issue by M-ds** [M-ds/Dashboard#62]
**Description**
As part to divide the projects resposibilities. I think it would be a good idea to also seperate the concers of the documentation. Meaning, the technical documentation should be just part of the repository. As it is not as important for the other users to read and know about the implementation and so on. 

And the regular documentation should just be a document stating what it is all about. Thus what the user can expect, how he/she can interact with the content and so on. 

**Todo**
- [x] copy the technical documentation to the wiki
- [x] create different chapters for each interactable link
- [x] in the welcome page a link should be displayed to each individual interactable
- [x] remove the technical information for the google doc document.
- [x] the technology stack just stay in the document (can be intereseting) + in the wiki
