### ISSUE TITLE
2.1 - Make sure the data typed in one screen, is another screen as well

### ISSUE THREAD

**Issue by M-ds** [M-ds/Dashboard#66]
**Description**
Make the data typed in one editor also visiable in another editor.
This is to make it easier for the users, to keep all their data in one place.

 **link**
https://vuex.vuejs.org/guide/modules.html
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

**Todo**
- [x] Add vuex
- [x] Create a link to the H2 database
- [x] Make sure the data is stored in the H2 database
- [x] Make sure the data is retrieved from the H2 database
- [x] display the obtained data
- [x] document

**Comment by M-ds** [comment]
Je moet zorgen dat je VUEX goed gaat begrijpen..
Dus misschien dit eens goed doorlezen https://vuex.vuejs.org/guide/

**Comment by M-ds** [comment]
https://medium.com/@harittweets/how-to-connect-to-h2-database-during-development-testing-using-spring-boot-44bbb287570

**Comment by M-ds** [comment]
Momenteel wordt de database goed aangemaakt. Alleen werkt nog niet helemaal goed. De juiste data wordt nog niet opgelsagen of goed opgehaald.

**Comment by M-ds** [comment]
https://proandroiddev.com/multiple-ways-of-defining-clean-architecture-layers-bbb70afa5d4a

**Comment by M-ds** [comment]
Momenteel word de data goed opgeslagen in de database, en dan weer terug opgehaald. 

Dit gebeurt dan voor alle verschillende projecten waar je de editor in gebruikt. Het enige wat moet gebeuren in de juiste methode aan te roepen.
