### ISSUE TITLE
2.1 - Make the Weather Forecast a different markup than the others

### ISSUE THREAD

**Issue by M-ds** [M-ds/Dashboard#67]
**Description**
Make the pages a bit darker in the background. Only the right-side (interactable details) need to catch the eye.
Create a draft to create a mindmap

**Todo**
- [x] Create a draft of the new page
- [x] Make the background of the page go a bit darker (so you have the feeling you're still on the same page, and only have a page on top of the older)
- [x] Document the layout
